server.port: ${itzy-micro-services.ports.gateway-service:8080}

#服务名
spring:
  cloud:
    gateway:
      routes:
        #netty 路由过滤器，http或https开头
        - id: app1-route
          uri: http://localhost:8081
          predicates:
            - Path=/app1/**
          filters:
            #转发请求时去掉1级前缀
            - StripPrefix=1